### ISSUE TITLE
Simple Web-UI possible?

### ISSUE THREAD

**Issue by nirvor** [KillianLucas/open-interpreter#1]
Hi!

I like your approach for using the gpt4 api with "expended" codeinterpeter really a lot. Is it maybe possible to give the "chat" input/output to a frontend for a local webserver UI? Like via streamlit? Iam still @learning, cant really help that much with frontends a.e., I guess.  But would really "boost" your nice concept.

**Comment by KillianLucas** [comment]
Thanks Nirvor!

Let's think about this, because I think it's a great idea, but I don't want to overcomplicate the project. I think we should try to keep it as minimal as possible so it's easy for someone new to understand the whole code base.

Given the current terminal UI, what do you think are the benefits of a more reactive webserver UI? Some ideas: dragging files into it, perhaps chat history, export `.py` files... Let me know if you have other ideas.

In the future, I think we should make a really simple app that would let people talk to Open Interpreter easily. It would basically be like a terminal interface / chat UI that doesn't require them to open a terminal. They could download it from the Mac store, or as an `.exe`. Thoughts?

**Comment by nirvor** [comment]
I have seen you already started, super! Looking forward to test it :-) 

-> 
I started trying to (and learn a bit in general...) do some basic pull request of the input/output of the open-interpreter command line chat and "streamlit" it to a local streamlit app.

But doing it via tailwind sounds really interesting, too (to follow, not sure if I can help that much...)  

After testing some GUIs (all with that "i forget everything during the sessions, no memory" of the openai API limitations... "bothers" me somehow the most...), some basic idea "features", without ( i think ) that its getting totally out of hand for a hobby project:

Certainly! Adding those considerations, the updated list becomes:

1. Text Input Field: Allow users to enter questions or requests.
2. Model Selection: Dropdown to choose specific GPT models 
(GPT3 switch "possible" with your approach, for "easy" tasks? thinking about the session file system...)
3. Output Window: Display the model's response (including code formatting and figure / picture posting ?)
4. History: Save and display previous interactions, like you do now via python command
5. Authentication & Access Control: Implement user authentication (as "landing page"?, if its not set already in .env or sys path)
6. Token & Character Status: Show status regarding token usage, max characters, max output, ...)
7. open-interpreter feature(!): A permanent session File System: Provide insights of the file system of the actual GPT session, if applicable. (Which paths knows the GPT session? Which files / scripts / documents / have been read into the database in this session?)
8. **Help & Documentation**: Link to Github etc...

( But: Its a nice feature to "open" the interpreter in a folder via terminal and let it edit/change/"do its work" within the folder! This would be most likely "lost" with a html gui...? )

I hope it helps! No feature request for sure, i would already be happy if I can copy the output of the interpreter out of a html chat instead of out of terminal.

**Comment by Kreijstal** [comment]
Terminal UI is buggy when scrolling, there are no libraries of web ui that do code interpreting??

**Comment by arnaujc91** [comment]
Are there any news regarding the desktop app if webbui is out of scope? 

Thanks!
