### ISSUE TITLE
Question: Where is the path to the model download?

### ISSUE THREAD

**Issue by tisfeng** [KillianLucas/open-interpreter#127]
I tried to run it  on macOS in local mode but failed, I want to delete the already downloaded model but I don't know the file path.

**Comment by andraz** [comment]
I managed to figure out one location to be inside homedir (~) /llama.cpp/models

Then you can put in there a manually downloaded file of the model and name it as one of these files:
https://github.com/KillianLucas/open-interpreter/blob/main/interpreter/llama_2.py#L18

I've got 13b-instruct.Q5, but I just renamed it to Q4 so it finds it.

```
    Directory: C:\Users\andra\llama.cpp\models


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        24/08/2023     22:33     9402834720 codellama-13b-instruct.Q4_K_M.gguf

```

**Comment by Binary-Bytes** [comment]
If you're on Mac, should be at `/Users/UserName/Library/Application Support/Open Interpreter/models/` folder. Not sure about windows.

**Comment by KillianLucas** [comment]
@jordanbtucker wrote this code snippet, which will locate Code Llama install folder on any operating system:

```
python -c 'import appdirs; print(appdirs.user_data_dir("Open Interpreter"))'
```

Let me know if that works! 

We're also going to print the download location when you select it in the next version, so you don't have to try to find it.

**Comment by c469591** [comment]
Hello, I would like to know where it stores the model on Windows. I can't seem to find its location. Thank you.

**Comment by c469591** [comment]
I found it.
C:\Users\Administrator\AppData\Local\Open Interpreter\Open Interpreter

**Comment by tisfeng** [comment]
@KillianLucas Thanks, but it's a bit strange, I don't see "Open Interpreter" under this path, does it automatically delete the model file when it fails to run?

 When I downloaded the model before, I watched the progress bar step by step and it took almost an hour, this should have downloaded successfully.

<img width="1051" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/25194972/55c6aba6-2a0b-41cb-87f0-250a66c792b4">

**Comment by webia1** [comment]
@tisfeng 

Should the installation process be interrupted for any reason (perhaps due to an Apple M1/M2 chipset, etc.), please be aware that the model will not be automatically removed from your system. It will remain in the following directories below and you would need to manually delete it.

For MacOS: `/Users/<user-name>/Library/Application Support/`  
For Windows: `..AppData\Local\Open Interpreter\Open Interpreter`

If you install Python on a Mac using the command `brew install python`, it will install version 3, which is executable with python3. To ascertain the location where the model has been copied, you would need to execute the following command: 

```shell
python3 -c 'import appdirs; print(appdirs.user_data_dir("Open Interpreter"))'
```

If you are utilizing an Apple M1/M2 chipset, you may attempt the installation following the guidelines provided in this link: [How to Install Llama in MacOS](https://www.toyoko.io/how-to-install-llama-in-macos/).

**Comment by JJery-web** [comment]
How can I change the path to the model download please. My C disk has no more space :(

**Comment by drhouse** [comment]
> How can I change the path to the model download please. My C disk has no more space :(

I had the same problem, so I made a symlink folder and it's downloading fine. A symlink connects two folders that have the same name and can be on different hard drives, it treats one like the other. So, for example, a C:\folder (low disk space) can be symlinked to N:\folder (lots of disk space). 

You can use this context-menu [tool ](https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html) or the 'mklink' command on console window (it's very easy). Check folder Properties to see if the symlink worked the way you wanted.

**Comment by sascharo** [comment]
> How can I change the path to the model download please. My C disk has no more space :(

Doesn't the environment variable `OLLAMA_MODELS` work for you?

**Comment by MaoJianwei** [comment]
For linux, here:

~/.llama/checkpoints/Llama3.2-1B-Instruct
