### ISSUE TITLE
a  bug  with "readline"

### ISSUE THREAD

**Issue by yizhangliu** [KillianLucas/open-interpreter#175]
Runtime Environment： Ubuntu 20.04.6 LTS \n \l  in  5.10.102.1-microsoft-standard-WSL2.
Python 3.11.5
After "pip install readline", I run "interpreter --fast -y":
> hi
double free or corruption (out)
Aborted

**Comment by jordanbtucker** [comment]
Thanks for reporting. Can you please fill out the following template to help us troubleshoot the issue.

Your issue may have already been reported. Please check the following link for common issues and solutions.

(Commonly faced issues and their solutions){https://github.com/KillianLucas/open-interpreter/issues/164}

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. iOS]
 - Python version [e.g. 3.10]
 - Open Interpreter version (`pip show open-interpreter`): [e.g. 0.1.1] 

**Additional context**
Add any other context about the problem here.

**Comment by ericrallen** [comment]
Hey there, @yizhangliu!

I'm going to close this one as stale for now, but feel free to reopen it if you want to provide some more context and still experience this issue with the latest version of Open Interpreter.
