### ISSUE TITLE
Failed to install Code-LLama

### ISSUE THREAD

**Issue by Raclez** [KillianLucas/open-interpreter#202]
`▌ Failed to install Code-LLama.

We have likely not built the proper Code-Llama support for your system.

( Running language models locally is a difficult task! If you have insight into the best way to implement this across
platforms/architectures, please join the Open Interpreter community Discord and consider contributing the project's development. )

Please press enter to switch to GPT-4 (recommended).`

Why can't I download it? How to select a model I don't have gpt-api

**Comment by jordanbtucker** [comment]
Please use the template provided to submit reports.

Your issue may have already been reported. Please check for [common issues and solutions](https://github.com/KillianLucas/open-interpreter/issues/164).

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. iOS]
 - Python version [e.g. 3.10]
 - Open Interpreter version (`pip show open-interpreter`): [e.g. 0.1.1] 

**Additional context**
Add any other context about the problem here.

**Comment by oalvay** [comment]
In my case, I manually ran `pip install llama-cpp-python` to solve this.

**Comment by UniverseMoon** [comment]
You can run cmd administrator with mode

**Comment by UniverseMoon** [comment]
You can run cmd with  administrator mode

**Comment by agent-Y** [comment]
I am using M2 macbook air 16gb 512gb. 
I downloaded and tried 'Parameter count:7B' and 'Quality:high' but got the above error. I installed 'Quality:low' instead and it started, although very slowly. Perhaps my computer specs were insufficient.

**Comment by ihgalis** [comment]
@Raclez does this help? https://github.com/KillianLucas/open-interpreter/blob/main/docs/MACOS.md

@agent-Y i have a similar device. use 13B with medium, which needs about 10 GB of RAM. close chrome before you do this. be aware that the macbook air has no active cooling. it could run very slowly after some time without cooling.

**Comment by agent-Y** [comment]
@ihgalis  It was also activated on 13B with medium. Thank you :)

**Comment by Raclez** [comment]
mac running code-liama is a bit difficult, it's better to use chatgpt4 I think

**Comment by fuhongxue00** [comment]
I get the same error and then I just try `interpreter` again. This time I didn't press Y when _"would you like to download it"_ and anyway it bagan to download without the error above.
Maybe it's just random bugs

**Comment by jordanbtucker** [comment]
Closing as issue owner did not fill out template.
