### ISSUE TITLE
Keyword Error issue

### ISSUE THREAD

**Issue by sohag02** [KillianLucas/open-interpreter#21]
![image](https://github.com/KillianLucas/open-interpreter/assets/70505164/8bfebde1-7812-4e80-bca0-26f36569fd69)

I am getting this issue sometimes. The same cmd which is to create a venv in this case works sometimes but sometimes it shows this error. It happens with other cmds too.

**Comment by nofeetbird0321** [comment]
Get the same issue.

**Comment by KillianLucas** [comment]
Hey @sohag02 and @nofeetbird0321, thanks for opening this issue.

I've gotten that when GPT-3.5 (`--fast` mode) tries to hallucinate a function, so we can't parse it correctly. I'll work on catching that / handling it correctly.

In the meantime you could try reiterating to it: "You have one function called run_code that accepts language and code. Do not use any function except for run_code." or something like that.

GPT-4 never seems to hallucinate functions so that should work to simply omit the `--fast` flag!
