### ISSUE TITLE
Fatal Python error: _Py_HashRandomization_Init: failed to get random numbers to initialize Python Python runtime state: preinitialized

### ISSUE THREAD

**Issue by ucyo123** [KillianLucas/open-interpreter#219]
Fatal Python error: _Py_HashRandomization_Init: failed to get random numbers to initialize Python
Python runtime state: preinitialized

Error during installation with cuBLAS: Command '['C:\\Users\\zh\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'pip',
'install', 'llama-cpp-python']' returned non-zero exit status 1.

**Comment by jordanbtucker** [comment]
Thanks for reporting. Can you please fill out the following form to help us troubleshoot the issue.

Your issue may have already been reported. Please check the following link for common issues and solutions.

[Commonly faced issues and their solutions](https://github.com/KillianLucas/open-interpreter/issues/164)

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. iOS]
 - Python version [e.g. 3.10]
 - Open Interpreter version (`pip show open-interpreter`): [e.g. 0.1.1] 

**Additional context**
Add any other context about the problem here.

**Comment by ericrallen** [comment]
Hey there, @ucyo123!

I'm going to close this one as stale for now, but feel encouraged to reopen it if you still experience the issue with the latest version of Open Interpreter and want to provide some more context to help us debug.
