### ISSUE TITLE
Research optimal model to tun on a given hardware 

### ISSUE THREAD

**Issue by kwikiel** [KillianLucas/open-interpreter#240]
Example use case: say user has MacBook m1 or above with either 8, 16 or 32 GB ram. There should be some basic info which model to use as say tiiuae/falcon-180B probably won't run on 8 gb MacBook. 

While it's not strictly related to the OI codebase it would significantly increase the local models usability.

**Comment by ericrallen** [comment]
I think the user has been given a lot of control and needs to take some responsibility for understanding which model they want to run locally and why they want to run that model.

I’m going to close this one because it sounds like an entirely separate project that would be valuable, but isn’t part of what I would think of as Open Interpreter’s core.

Anyone please feel encouraged to correct me if I’m wrong and reopen the Issue.
