### ISSUE TITLE
Accept file as an Input

### ISSUE THREAD

**Issue by sankethgadadinni** [KillianLucas/open-interpreter#3]
are you planning to accept files as an input?

**Comment by KillianLucas** [comment]
Hi @sankethgadadinni! Yes, in fact on some operating systems [like Mac](https://support.apple.com/guide/terminal/drag-items-into-a-terminal-window-trml106/mac) you can already do this by dragging a file into your terminal. This will paste in the file or folder's absolute path, which is all Open Interpreter needs to work with it. We should add a video demo soon:

```python
$: interpreter
> Hey can you resize this photo to 1000x1000? **(drag file in here, which pastes its absolute path)** /Users/killianlucas/Desktop/photo.png

  Sure, I can help with that. Here's the plan:

  1. First, I will check if the required Python library PIL (Pillow) is installed on your system. If not, I will install it...
```

Related: #1 for a discussion of a UI that would support file dropping, conversation history, image display, etc. We'll need to do this to support operating systems that don't support dragging and dropping into terminal, or figure out how to use `curses` or [`dragon`](https://github.com/mwh/dragon).

**Comment by nirvor** [comment]
>  It would be great if we knew which systems supported this behavior (I only know Mac does) then we could add that to the documentation.

I tested it (dragging a file into the interpreter chat CLI  + see if the path gets pasted + if the interpreter finds the path and file) with
 
- Ubuntu 23 
- Windows 11 CLI

 --> Worked on both systems, too, without issues

**Comment by KillianLucas** [comment]
Thanks @nirvor! Just updated the documentation [with a demo.](https://github.com/KillianLucas/open-interpreter/tree/main#demos)

I think we can consider drag-and-drop to be a core/supported feature of Open Interpreter instead of specifying supported systems — Windows + Ubuntu + Mac is cross-platform enough for me. Let's make a note in the docs of it _not_ working on any systems/terminals though, if we find them.

**Comment by KillianLucas** [comment]
Thanks @nirvor! Just updated the documentation [with a demo.](https://github.com/KillianLucas/open-interpreter/tree/main#demos)

I think we can consider drag-and-drop to be a core/supported feature of Open Interpreter instead of specifying supported systems — Windows + Ubuntu + Mac is cross-platform enough for me. Let's make a note in the docs of it _not_ working on any systems/terminals though, if we find them.
