### ISSUE TITLE
Llama does not finish...

### ISSUE THREAD

**Issue by HexHands** [KillianLucas/open-interpreter#30]
I downloaded the Code Llama 7B, Medium. It seems to not finish any text meaning that it never executes the code. Is there any way of fixing this?
![Capture](https://github.com/KillianLucas/open-interpreter/assets/119904427/9d8d55b4-9ec3-4e66-92f8-efe7038eb9b2)

**Comment by KillianLucas** [comment]
Thanks for pointing this out @HexHands! 

We should probably have some sort of message that says when it completes because it hits `max_tokens` (which might be happening here?) . Then we could perhaps ask the user if they want to run the unfinished code block. 

Does it do this for very small snippets on your system, like "print hello world"? That will help us determine if it's a `max_tokens` issue.

**Comment by HexHands** [comment]
This is the best result I got. It runs the code, but for longer code it doesn't finish it. I would like the ability to be able to set max tokens using code.
![Capture](https://github.com/KillianLucas/open-interpreter/assets/119904427/ef2e6aea-ce76-4133-88dd-1c7e58a2053f)

**Comment by TheWhiteWord** [comment]
same problem

**Comment by brunoboto96** [comment]
Fiy, this was also reference by me here: https://github.com/KillianLucas/open-interpreter/issues/126#issuecomment-1712308763
Even though I've changed the context size on the appropriate files, even had a brief go at tokentrim.py but no luck

**Comment by brunoboto96** [comment]
https://github.com/KillianLucas/open-interpreter/issues/126#issuecomment-1714194767 Thanks @jordanbtucker  the refactoring now works by editing the params in interpreter.py 
Still a bit buggy in between instructions, but at least it does not stop 🚀

**Comment by leifktaylor** [comment]
**This issue looks resolved** based on @brunoboto96 comment.

@jordanbtucker
