### ISSUE TITLE
Running error in windows.

### ISSUE THREAD

**Issue by meloseven** [KillianLucas/open-interpreter#301]
### Describe the bug

when I first installed open-interpreter,then I ask to open new Tab in Chrome,then the error below comes out.

![image](https://github.com/KillianLucas/open-interpreter/assets/5311284/7b7ed60c-53d3-41ff-86bb-cc74bb9a76ad)

### Reproduce

1.`$ interpreter --fast`
2.请在chrome里新开一个窗口页，并打开google.com
3.Would you like to run this code? (y/n)
  y
4.then the error will coming out.

### Expected behavior

no error, works fine

### Open Interpreter version

0.1.3

### Python version

3.11.5

### Operating System name and version

windows 11

**Comment by jackfood** [comment]
Maybe you need to improve your prompt, stating Ur directory of your chrome. I remember for edge, you need to add on edge driver and some pip installation for it to work.

**Comment by meloseven** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ericrallen** [comment]
I’m going to close this one as stale for now.

AppleScriot can tell a Mac application to open and do something, but depending in your operating system this will need to be approached differently.

It’s also worth considering if it’s worth it to spend tokens on just opening an application.

Web browsing or scraping can be done programmatically if you’re looking to have Open Interpreter do something with the content of a web page, but you’ll want to ask it to scrape content from a site rather than asking it to open in your web browser.
