### ISSUE TITLE
unable to install on macos

### ISSUE THREAD

**Issue by pengzhangzhi** [KillianLucas/open-interpreter#49]
```
pengzhangzhi@pengzhangzhideMacBook-Air ~ % pip3 install open-interpreter
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement open-interpreter (from versions: none)
ERROR: No matching distribution found for open-interpreter
```

**Comment by KillianLucas** [comment]
Hi @pengzhangzhi! I'd recommend first trying to upgrade `pip` then trying to reinstall `open-interpreter`:

```
pip install --upgrade pip
pip install open-interpreter
```

If that doesn't work, let me know your `python --version` and we can go from there. Thanks!

**Comment by ariconnect** [comment]
I encountered the same problem. I am using python 3.11.5 and Pip 23.2.1 on a Mac. See the full error below. Please advise-
Defaulting to user installation because normal site-packages is not writeable
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.10,<4.0; 0.0.2 Requires-Python >=3.10,<4.0; 0.0.21 Requires-Python >=3.10,<4.0; 0.0.22 Requires-Python >=3.10,<4.0; 0.0.221 Requires-Python >=3.10,<4.0; 0.0.222 Requires-Python >=3.10,<4.0; 0.0.223 Requires-Python >=3.10,<4.0; 0.0.224 Requires-Python >=3.10,<4.0; 0.0.225 Requires-Python >=3.10,<4.0; 0.0.226 Requires-Python >=3.10,<4.0; 0.0.227 Requires-Python >=3.10,<4.0; 0.0.228 Requires-Python >=3.10,<4.0; 0.0.229 Requires-Python >=3.10,<4.0; 0.0.230 Requires-Python >=3.10,<4.0; 0.0.231 Requires-Python >=3.10,<4.0; 0.0.232 Requires-Python >=3.10,<4.0; 0.0.233 Requires-Python >=3.10,<4.0; 0.0.234 Requires-Python >=3.10,<4.0; 0.0.235 Requires-Python >=3.10,<4.0; 0.0.236 Requires-Python >=3.10,<4.0; 0.0.237 Requires-Python >=3.10,<4.0; 0.0.238 Requires-Python >=3.10,<4.0; 0.0.239 Requires-Python >=3.10,<4.0; 0.0.240 Requires-Python >=3.10,<4.0; 0.0.241 Requires-Python >=3.10,<4.0; 0.0.242 Requires-Python >=3.10,<4.0; 0.0.243 Requires-Python >=3.10,<4.0; 0.0.244 Requires-Python >=3.10,<4.0; 0.0.245 Requires-Python >=3.10,<4.0; 0.0.246 Requires-Python >=3.10,<4.0; 0.0.247 Requires-Python >=3.10,<4.0; 0.0.248 Requires-Python >=3.10,<4.0; 0.0.249 Requires-Python >=3.10,<4.0; 0.0.250 Requires-Python >=3.10,<4.0; 0.0.251 Requires-Python >=3.10,<4.0; 0.0.252 Requires-Python >=3.10,<4.0; 0.0.253 Requires-Python >=3.10,<4.0; 0.0.254 Requires-Python >=3.10,<4.0; 0.0.255 Requires-Python >=3.10,<4.0; 0.0.256 Requires-Python >=3.10,<4.0; 0.0.257 Requires-Python >=3.10,<4.0; 0.0.258 Requires-Python >=3.10,<4.0; 0.0.259 Requires-Python >=3.10,<4.0; 0.0.260 Requires-Python >=3.10,<4.0; 0.0.261 Requires-Python >=3.10,<4.0; 0.0.262 Requires-Python >=3.10,<4.0; 0.0.263 Requires-Python >=3.10,<4.0; 0.0.264 Requires-Python >=3.10,<4.0; 0.0.265 Requires-Python >=3.10,<4.0; 0.0.266 Requires-Python >=3.10,<4.0; 0.0.267 Requires-Python >=3.10,<4.0; 0.0.268 Requires-Python >=3.10,<4.0; 0.0.269 Requires-Python >=3.10,<4.0; 0.0.270 Requires-Python >=3.10,<4.0; 0.0.271 Requires-Python >=3.10,<4.0; 0.0.272 Requires-Python >=3.10,<4.0; 0.0.273 Requires-Python >=3.10,<4.0; 0.0.274 Requires-Python >=3.10,<4.0; 0.0.275 Requires-Python >=3.10,<4.0; 0.0.276 Requires-Python >=3.10,<4.0; 0.0.277 Requires-Python >=3.10,<4.0; 0.0.278 Requires-Python >=3.10,<4.0; 0.0.279 Requires-Python >=3.10,<4.0; 0.0.280 Requires-Python >=3.10,<4.0; 0.0.281 Requires-Python >=3.10,<4.0; 0.0.282 Requires-Python >=3.10,<4.0; 0.0.283 Requires-Python >=3.10,<4.0; 0.0.284 Requires-Python >=3.10,<4.0; 0.0.285 Requires-Python >=3.10,<4.0; 0.0.286 Requires-Python >=3.10,<4.0; 0.0.287 Requires-Python >=3.10,<4.0; 0.0.288 Requires-Python >=3.10,<4.0; 0.0.289 Requires-Python >=3.10,<4.0; 0.0.290 Requires-Python >=3.10,<4.0; 0.0.291 Requires-Python >=3.10,<4.0; 0.0.292 Requires-Python >=3.10,<4.0; 0.0.293 Requires-Python >=3.10,<4.0; 0.0.294 Requires-Python >=3.10,<4.0; 0.0.295 Requires-Python >=3.10,<4.0; 0.0.296 Requires-Python >=3.10,<4.0; 0.0.297 Requires-Python >=3.10,<4.0; 0.1.0 Requires-Python >=3.10,<4.0
ERROR: Could not find a version that satisfies the requirement open-interpreter (from versions: none)
ERROR: No matching distribution found for open-interpreter

**Comment by huhaosanxiong** [comment]
same issue

**Comment by Cursky** [comment]
python 3.9.12 
Must be python vision >3.10 ?
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.10,<4.0; 0.0.2 Requires-Python >=3.10,<4.0; 0.0.21 Requires-Python >=3.10,<4.0; 0.0.22 Requires-Python >=3.10,<4.0; 0.0.221 Requires-Python >=3.10,<4.0; 0.0.222 Requires-Python >=3.10,<4.0; 0.0.223 Requires-Python >=3.10,<4.0; 0.0.224 Requires-Python >=3.10,<4.0; 0.0.225 Requires-Python >=3.10,<4.0; 0.0.226 Requires-Python >=3.10,<4.0; 0.0.227 Requires-Python >=3.10,<4.0; 0.0.228 Requires-Python >=3.10,<4.0; 0.0.229 Requires-Python >=3.10,<4.0; 0.0.230 Requires-Python >=3.10,<4.0; 0.0.231 Requires-Python >=3.10,<4.0; 0.0.232 Requires-Python >=3.10,<4.0; 0.0.233 Requires-Python >=3.10,<4.0; 0.0.234 Requires-Python >=3.10,<4.0; 0.0.235 Requires-Python >=3.10,<4.0; 0.0.236 Requires-Python >=3.10,<4.0; 0.0.237 Requires-Python >=3.10,<4.0; 0.0.238 Requires-Python >=3.10,<4.0; 0.0.239 Requires-Python >=3.10,<4.0; 0.0.240 Requires-Python >=3.10,<4.0; 0.0.241 Requires-Python >=3.10,<4.0; 0.0.242 Requires-Python >=3.10,<4.0; 0.0.243 Requires-Python >=3.10,<4.0; 0.0.244 Requires-Python >=3.10,<4.0; 0.0.245 Requires-Python >=3.10,<4.0; 0.0.246 Requires-Python >=3.10,<4.0; 0.0.247 Requires-Python >=3.10,<4.0; 0.0.248 Requires-Python >=3.10,<4.0; 0.0.249 Requires-Python >=3.10,<4.0; 0.0.250 Requires-Python >=3.10,<4.0; 0.0.251 Requires-Python >=3.10,<4.0; 0.0.252 Requires-Python >=3.10,<4.0; 0.0.253 Requires-Python >=3.10,<4.0; 0.0.254 Requires-Python >=3.10,<4.0; 0.0.255 Requires-Python >=3.10,<4.0; 0.0.256 Requires-Python >=3.10,<4.0; 0.0.257 Requires-Python >=3.10,<4.0; 0.0.258 Requires-Python >=3.10,<4.0; 0.0.259 Requires-Python >=3.10,<4.0; 0.0.260 Requires-Python >=3.10,<4.0; 0.0.261 Requires-Python >=3.10,<4.0; 0.0.262 Requires-Python >=3.10,<4.0; 0.0.263 Requires-Python >=3.10,<4.0; 0.0.264 Requires-Python >=3.10,<4.0; 0.0.265 Requires-Python >=3.10,<4.0; 0.0.266 Requires-Python >=3.10,<4.0; 0.0.267 Requires-Python >=3.10,<4.0; 0.0.268 Requires-Python >=3.10,<4.0; 0.0.269 Requires-Python >=3.10,<4.0; 0.0.270 Requires-Python >=3.10,<4.0; 0.0.271 Requires-Python >=3.10,<4.0; 0.0.272 Requires-Python >=3.10,<4.0; 0.0.273 Requires-Python >=3.10,<4.0; 0.0.274 Requires-Python >=3.10,<4.0; 0.0.275 Requires-Python >=3.10,<4.0; 0.0.276 Requires-Python >=3.10,<4.0; 0.0.277 Requires-Python >=3.10,<4.0; 0.0.278 Requires-Python >=3.10,<4.0; 0.0.279 Requires-Python >=3.10,<4.0; 0.0.280 Requires-Python >=3.10,<4.0; 0.0.281 Requires-Python >=3.10,<4.0; 0.0.282 Requires-Python >=3.10,<4.0; 0.0.283 Requires-Python >=3.10,<4.0; 0.0.284 Requires-Python >=3.10,<4.0; 0.0.285 Requires-Python >=3.10,<4.0; 0.0.286 Requires-Python >=3.10,<4.0; 0.0.287 Requires-Python >=3.10,<4.0; 0.0.288 Requires-Python >=3.10,<4.0; 0.0.289 Requires-Python >=3.10,<4.0; 0.0.290 Requires-Python >=3.10,<4.0; 0.0.291 Requires-Python >=3.10,<4.0; 0.0.292 Requires-Python >=3.10,<4.0; 0.0.293 Requires-Python >=3.10,<4.0; 0.0.294 Requires-Python >=3.10,<4.0; 0.0.295 Requires-Python >=3.10,<4.0; 0.0.296 Requires-Python >=3.10,<4.0; 0.0.297 Requires-Python >=3.10,<4.0; 0.1.0 Requires-Python >=3.10,<4.0
ERROR: Could not find a version that satisfies the requirement open-interpreter (from versions: none)
ERROR: No matching distribution found for open-interpreter

**Comment by mooxl** [comment]
Yes, the version must be >=3.10.
I encountered the same error and investigated the version used by `pip/pip3` with `pip --version`. I discovered that it was 3.9. After installing the new version of Python and updating the path in `.zshrc/.bashrc`, everything started working.

**Comment by rookasrudzianskas** [comment]
Exactly! Just had the issue as well, and the version must be `>= 3.10`.

**Comment by lxysl** [comment]
Create a new conda environment with python >= 3.10 works for me.

**Comment by ee0pdt** [comment]
Create new conda env:

`conda create --name code-interp python=3.10`

Activate the new env:

`conda activate code-interp`

Install open-interpreter

`pip install open-interpreter`

**Comment by AdelleBernal** [comment]
You mean source activate? :)

**Comment by jordanbtucker** [comment]
> You mean source activate? :)

👀 I haven't used `source activate` since 2017

**Comment by AdelleBernal** [comment]
Why am I getting this then?
```
 conda activate code-interp

CommandNotFoundError: 'activate is not a conda command.
Did you mean 'source activate'?
```

**Comment by jordanbtucker** [comment]
Probably because you need to use the `conda init` command to configure it for your shell.

**Comment by AdelleBernal** [comment]
I'm a newbie, so I am a bit lost. conda init
usage: conda [-h] [-V] command ...
conda: error: argument command: invalid choice: '/usr/local/anaconda3/bin/conda' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')

**Comment by jordanbtucker** [comment]
You must be running a conda version older than 4.4, which was released in 2017.

**Comment by AdelleBernal** [comment]
conda --version
conda 4.3.30
