### ISSUE TITLE
Graceful interruption of text generation or running scripts

### ISSUE THREAD

**Issue by AncalagonX** [KillianLucas/open-interpreter#575]
### Is your feature request related to a problem? Please describe.

Is there a way to gracefully interrupt the interpreter if it's not generating what we want? CTRL+C works, but it introduces issues because the interpreter gets de-synced with itself in some way.

### Describe the solution you'd like

Pressing `[Escape]` should cause the text generation to cease, and return control to the user. It should also probably append a message such as `User manually interrupted your writing.` at that point, as well.

This interruption should be robust against interrupting raw text generation, code generation, or actively executing scripts.

**Comment by KillianLucas** [comment]
Great idea @Ancalagon. We should look into ways we can detect `ESC` -- Ctrl-C should also work but yes, it's quite messy because it's also the `Keyboard Interrupt` signal.On Oct 2, 2023, at 1:36 PM, Ancalagon ***@***.***> wrote:﻿
Is your feature request related to a problem? Please describe.
Is there a way to gracefully interrupt the interpreter if it's not generating what we want? CTRL+C works, but it introduces issues because the interpreter gets de-synced with itself in some way.
Describe the solution you'd like
Pressing [Escape] should cause the text generation to cease, and return control to the user. It should also probably append a message such as User manually interrupted your writing. at that point, as well.
Describe alternatives you've considered
No response
Additional context
No response

**Comment by slavakurilyak** [comment]
In Python, you can use the ﻿[KeyboardInterrupt](https://docs.python.org/3/library/exceptions.html#KeyboardInterrupt) (built-in exception) when the user hits the interrupt key (normally Control-C or Delete)

**Comment by moymoussan** [comment]
Bumping
Very often for some reason the interpreter stops answering (or streaming) or even does not start answering at all, when pressing ctrl+c sometimes it interrupts correctly and returns to the chat (> ) and sometimes this is the behavior:
<img width="382" alt="Captura de pantalla 2023-10-27 a la(s) 1 10 54 a m" src="https://github.com/KillianLucas/open-interpreter/assets/66051741/a4eef74f-ff02-47ae-9745-f2ef852737a1">

<img width="382" alt="Captura de pantalla 2023-10-27 a la(s) 1 18 14 a m" src="https://github.com/KillianLucas/open-interpreter/assets/66051741/f72ea392-6e63-4df8-b1a3-4aea92444356">

For every "Failed to parse..." printed on the terminal, a ctrl+c preceded it.

**Comment by MikeBirdTech** [comment]
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!
