### ISSUE TITLE
Open Interpreter is getting stuck

### ISSUE THREAD

**Issue by SparshMittalAI** [KillianLucas/open-interpreter#613]
### Describe the bug

Open Interpreter is getting stuck when I run task via Python script as well as Interactive environment.

### Reproduce

For Python script - 
import interpreter
interpreter.auto_run = True
interpreter.reset()
interpreter.chat("Can you solve this equation? 10x + 14 = 21 / 3")

For Interactive env - 
Run - interpreter
Then - Can you solve this equation? 10x + 14 = 21 / 3

### Expected behavior

It should proceed with installing relevant package as I am running python script in auto_run

### Screenshots

![image](https://github.com/KillianLucas/open-interpreter/assets/119413462/8cca035a-38d4-4d5f-925c-f451de320f07)

### Open Interpreter version

0.1.7

### Python version

3.11.5

### Operating System name and version

Ubuntu 18.04.5 LTS

**Comment by ericrallen** [comment]
Hey there, @SparshMittalAI!

I’m going to close this one as I believe this one was fixed in a later version of Open Interpreter with some logic that removes the Jupyter Notebook style `!` from the `pip install` command before trying to execute it.

Please feel encouraged to reopen the issue if I’m wrong.
