### ISSUE TITLE
Failed to run open-interpreter for openai API compatible server for local LLMs

### ISSUE THREAD

**Issue by wuyongyi** [KillianLucas/open-interpreter#653]
### Describe the bug

I use:
 

litellm --model ollama/codellama

to setup openai API compatible server for local LLMs in http://0.0.0.0:8000/

as (https://docs.litellm.ai/docs/providers/ollama)

The test code for litellm itself works fine. 

But I get error in connection with open-interpreter:
"""

model, custom_llm_provider = get_llm_provider(model=model, custom_llm_provider=custom_llm_provider, api_base=api_base)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ProgramData\anaconda3\Lib\site-packages\litellm\utils.py", line 1483, in get_llm_provider
raise e
File "D:\ProgramData\anaconda3\Lib\site-packages\litellm\utils.py", line 1480, in get_llm_provider
raise ValueError(f"LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in completion(model='huggingface/{model}',..) Learn more: https://docs.litellm.ai/docs/providers")

...

raise APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model)
litellm.exceptions.APIError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in completion(model='huggingface/gpt-4',..) Learn more: https://docs.litellm.ai/docs/providers
"""

### Reproduce

1. litellm --model ollama/codellama

2. run interpreter connect to http://0.0.0.0:8000/

### Expected behavior

work as connection to openai

### Open Interpreter version

0.1.9

### Python version

3.11.5

### Operating System name and version

windows 10

**Comment by KillianLucas** [comment]
I think we should make this happen automatically, but I believe the fix for this is:```interpreter --model openai/codellama --api_base http://0.0.0.0:8000/```Which should set the custom_llm_provider in LLM (essentially the "api type") to OpenAI.Let me know if that doesn't work.On Oct 18, 2023, at 7:34 AM, LambdaX ***@***.***> wrote:﻿
Describe the bug
I use:
litellm --model ollama/codellama
to setup openai API compatible server for local LLMs in http://0.0.0.0:8000/
as (https://docs.litellm.ai/docs/providers/ollama)
The test code for litellm itself works fine.
But I get error in connection with open-interpreter:
"""
model, custom_llm_provider = get_llm_provider(model=model, custom_llm_provider=custom_llm_provider, api_base=api_base)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ProgramData\anaconda3\Lib\site-packages\litellm\utils.py", line 1483, in get_llm_provider
raise e
File "D:\ProgramData\anaconda3\Lib\site-packages\litellm\utils.py", line 1480, in get_llm_provider
raise ValueError(f"LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in completion(model='huggingface/{model}',..) Learn more: https://docs.litellm.ai/docs/providers")
...
raise APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model)
litellm.exceptions.APIError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in completion(model='huggingface/gpt-4',..) Learn more: https://docs.litellm.ai/docs/providers
"""
Reproduce


litellm --model ollama/codellama


run interpreter connect to http://0.0.0.0:8000/


Expected behavior
work as connection to openai
Screenshots
No response
Open Interpreter version
0.1.9
Python version
3.11.5
Operating System name and version
windows 10
Additional context
No response

**Comment by wuyongyi** [comment]
Thanks for reply. now the connection seems fine. 
what I run:
 interpreter --model openai/codellama --api_base http://127.0.0.1:8000/
my ollama is in a wsl2 system in order to use cuda, while open-interpreter is  from powershell, so the 0.0.0.0 does not work.
