### ISSUE TITLE
Support for python3.9 and docker image

### ISSUE THREAD

**Issue by Chandrahas-B** [KillianLucas/open-interpreter#72]
Hey @KillianLucas , I was able to run the interpreter with <b> python 3.9 </b>, can I PR for the same?

Also, would it be beneficial to create a docker image for the project?

**Comment by Chandrahas-B** [comment]
Yes @guesshe , a minimum Python version of 3.10 is required.

**Comment by yunielrc** [comment]
Create a vedv image with https://github.com/yunielrc/vedv

**Comment by sammcj** [comment]
Docker image would be nice! Python3.9 is pretty old though I'm not sure why you'd want that.

**Comment by leifktaylor** [comment]
This issue is dual scoped:
1) asking for 3.9 support
2) asking for containerization of open-interpreter

The associated PR adds a possible docker implementation using docker-compose.  However I believe there are issues with the usability of the Docker implementation in that (comment here: https://github.com/KillianLucas/open-interpreter/pull/204#issuecomment-1763514271)

**Recommend closing this issue** as 3.9 support is not in scope, and Docker implementation should be something discussed at length with stakeholders.

@jordanbtucker @KillianLucas
