### ISSUE TITLE
Support OSS model serving (ollama etc)

### ISSUE THREAD

**Issue by JayDoubleu** [KillianLucas/open-interpreter#777]
### Is your feature request related to a problem? Please describe.

Currently to use open-interpreter I need to install a closed source application 

### Describe the solution you'd like

I would like to use the open source alternative

**Comment by ericrallen** [comment]
Hey there, @JayDoubleu!

You’re free to use anything that the underlying [LiteLLM integration](https://docs.litellm.ai/docs/providers) supports.

For example, you could use Ollama for your local models instead of LM Studio.

LM Studio is just the default because it simplifies the process of running and tweaking local modes for the average user.

**Comment by whoabuddy** [comment]
+1, would like to use this with [textgen-web-ui](https://github.com/oobabooga/text-generation-webui) using the OpenAI replacement endpoints as well.

**Comment by ericrallen** [comment]
Hey there, @whoabuddy!

I believe you should be able to use the [`api_base` functionality from the underlying LiteLLM integration](https://docs.litellm.ai/docs/providers/custom_openai_proxy) to do that.

**Comment by Notnaton** [comment]
@ericrallen Seems like people have problems connecting to [textgen-web-ui](https://github.com/oobabooga/text-generation-webui) https://discord.com/channels/1146610656779440188/1146610657224040451/1177381909467254854
