### ISSUE TITLE
I'm using Interpreter on macOS, but I'm unable to interact with the computer

### ISSUE THREAD

**Issue by shawokou123** [KillianLucas/open-interpreter#86]
I'm using gpt-3.5, but why can't I execute tasks properly, like opening the  Chrome browser? When I try to have it perform this task, I receive the     following message:
I'm sorry for any misunderstanding, but I don't have the capability to        
  directly interact with applications on your local machine. However, you can   
  easily open the Chrome app on your macOS by following these steps:            
                                                                                
   1 Go to your Applications folder.                                            
   2 Find the Google Chrome app.                                                
   3 Double-click on it to open.                                                
                                                                                
  If you have any further questions or need assistance with something else,     
  feel free to let me know!   

what can i do?

**Comment by yunielrc** [comment]
Create a vedv image with https://github.com/yunielrc/vedv

**Comment by ericrallen** [comment]
For something like opening the browser, you'd probably be better off clicking on your `Google Chrome.app`, using Spotlight (`CMD` + `Space`) and searching for `Chrome`, or using `open` with a URL (*Example*: `open https://google.com/`), etc. rather than spending tokens on it.

However, if you want to have the browser do stuff, you can ask for an AppleScript that [executes some actions in the browser](https://apple.stackexchange.com/a/92666).

If you're looking to automate a bunch of browser stuff, you're pr)obably better served by using something like [Playwright](https://playwright.dev/) and getting Open Interpreter to help you create your Playwright script.

**Comment by ericrallen** [comment]
Hey there, @shawokou123!

Is there anything else with this one that you need help with?

Did you try any of the suggestions?

**Comment by shawokou123** [comment]
> Hey there, @shawokou123!
> 
> Is there anything else with this one that you need help with?
> 
> Did you try any of the suggestions
Thank you, I've fixed this issue, thanks again
